// High-frequency ComfyUI vocabulary used only when no curated dictionary entry exists.
// Product/model names are deliberately preserved.
export const PHRASES = Object.freeze({
  "lo ra": "LoRA",
  "open ai": "OpenAI",
  "chat gpt": "ChatGPT",
  "audio di t": "AudioDiT",
  "long cat": "LongCat",
  "fish speech": "FishSpeech",
  "custom data reader": "自定义数据读取器",
  "naiba textbox": "naiba文本盒",
  "naiba node": "naiba 节点",
  "visual lora loader": "可视化LoRA加载器",
  "naiba wan block swap": "naibawan模型分块卸载节点",
  "triggerwords": "LoRA 触发词",
  "trigger words": "触发词",
  "lora trigger words": "LoRA 触发词",
  "lo ra trigger words": "LoRA 触发词",
  "load images for loop": "加载图像并循环",
  "load image": "加载图像",
  "save image": "保存图像",
  "load model": "加载模型",
  "model loader": "模型加载器",
  "lora loader": "LoRA加载器",
  "vae loader": "VAE 加载器",
  "control net": "ControlNet",
  "control net loader": "ControlNet 加载器",
  "text encode": "文本编码",
  "text encoder": "文本编码器",
  "image batch": "图像批次",
  "batch size": "批次大小",
  "image size": "图像尺寸",
  "width and height": "宽度和高度",
  "positive prompt": "正向提示词",
  "negative prompt": "负向提示词",
  "start index": "起始索引",
  "end index": "结束索引",
  "initial value": "初始值",
  "preview image": "预览图像",
  "custom prompt": "自定义提示词",
  "model description": "模型描述",
  "download link": "下载链接",
  "raw json": "原始 JSON",
  "file name": "文件名",
  "file path": "文件路径",
  "output path": "输出路径",
  "input image": "输入图像",
  "output image": "输出图像",
  "source image": "源图像",
  "target image": "目标图像",
  "random seed": "随机种子",
  "sampling steps": "采样步数",
  "frame rate": "帧率",
  "frame count": "帧数",
  "first frame": "首帧",
  "last frame": "尾帧",
  "audio file": "音频文件",
  "video file": "视频文件",
  "system prompt": "系统提示词",
  "user prompt": "用户提示词",
  "base model": "基础模型",
  "output model": "输出模型",
  "input directory": "输入目录",
  "output directory": "输出目录",
  "keep aspect ratio": "保持宽高比",
  "aspect ratio": "宽高比",
  "resize mode": "缩放模式",
  "crop mode": "裁剪模式",
  "blend mode": "混合模式",
  "mask mode": "遮罩模式",
  "color space": "色彩空间",
  "device mode": "设备模式",
  "precision mode": "精度模式",
  "clear cache": "清理缓存",
  "free memory": "释放内存",
  "enable preview": "启用预览",
  "force offload": "强制卸载",
  "use cache": "使用缓存",
  "default value": "默认值",
  "join string multi": "多字符串拼接",
  "inputcount": "输入数量",
  "input count": "输入数量",
  "return list": "返回列表",
  "filename prefix": "文件名前缀",
  "stop at clip layer": "停止于 CLIP 层",
  "grow mask by": "遮罩扩展量",
  "upscale method": "放大方法",
  "scale by": "按比例缩放",
  "extra pnginfo": "额外 PNG 信息",
  "conditioning to strength": "目标条件强度",
  "conditioning to": "目标条件",
  "set cond area": "设置条件区域",
  "start at step": "起始步",
  "end at step": "结束步",
  "blend factor": "混合系数",
  "weight dtype": "权重数据类型",
  "clip vision": "CLIP 视觉模型",
  "clip vision output": "CLIP 视觉输出",
  "strength model": "模型强度",
  "low threshold": "低阈值",
  "high threshold": "高阈值",
  "match image size": "匹配图像尺寸",
  "unique id": "唯一 ID",
  "learning rate": "学习率",
  "gradient checkpointing": "梯度检查点",
  "existing lora": "现有 LoRA",
  "cell width": "单元格宽度",
  "cell height": "单元格高度",
  "blocks to swap": "交换分块数",
  "prefetch blocks": "预取分块数",
  "shorter edge": "较短边",
  "longer edge": "较长边",
  "max length": "最大长度",
  "min length": "最小长度",
  "max depth": "最大深度",
  "min padding": "最小边距",
  "kernel size": "内核尺寸",
  "source stats": "源统计信息",
  "crop region": "裁剪区域",
  "resize type": "缩放类型",
  "scale method": "缩放方法",
  "blur radius": "模糊半径",
  "sharpen radius": "锐化半径",
  "noise augmentation": "噪声增强",
  "augmentation level": "增强级别",
  "motion bucket id": "运动桶 ID",
  "largest size": "最大尺寸",
  "final width": "最终宽度",
  "final height": "最终高度",
  "spacing width": "间距宽度",
  "spacing color": "间距颜色",
  "loss function": "损失函数",
  "training dtype": "训练数据类型",
  "lora dtype": "LoRA 数据类型",
  "quantized backward": "量化反向传播",
  "upscale image by": "按比例放大图像",
  "upscale latent by": "按比例放大潜空间",
  "re actor": "ReActor",
  "return with leftover noise": "携带剩余噪声返回"
});

export const WORDS = Object.freeze({
  a: "一个", add: "添加", advanced: "高级", align: "对齐", alpha: "透明度",
  amount: "数量", analyze: "分析", and: "和", any: "任意", apply: "应用", area: "区域", aspect: "宽高比", audio: "音频",
  auto: "自动", background: "背景", batch: "批次", blend: "混合", blur: "模糊",
  boolean: "布尔值", box: "框", brightness: "亮度", cache: "缓存", calculate: "计算",
  actor: "角色", attention: "注意力", attn: "注意力", basic: "基础", base: "基础", bbox: "边界框", bg: "背景", binary: "二进制", block: "分块", blocks: "分块", by: "按", caption: "描述", camera: "相机",
  cell: "单元格", chan: "通道", channel: "通道", chat: "对话", checkpoint: "检查点模型", ckpt: "检查点模型", choose: "选择", clean: "清理",
  clip: "CLIP", color: "颜色", combine: "合并", compact: "紧凑", compare: "比较",
  columns: "列", compile: "编译", complete: "补全", composite: "合成", compress: "压缩", cross: "交叉",
  compression: "压缩", concatenate: "拼接", concat: "拼接", cond: "条件", condition: "条件",
  conditioning: "条件", config: "配置", context: "上下文", control: "控制", convert: "转换", copy: "复制",
  count: "数量", create: "创建", crop: "裁剪", custom: "自定义", data: "数据",
  debug: "调试", decode: "解码", decoder: "解码器", default: "默认", delete: "删除", delimiter: "分隔符", dictionary: "字典",
  denoise: "降噪", deprecated: "已弃用", depth: "深度", description: "描述", destination: "目标",
  detailer: "细化器", detect: "检测", detector: "检测器", device: "设备", diffusion: "扩散", directory: "目录",
  disable: "禁用", dither: "抖动", double: "双重", download: "下载", draw: "绘制", duration: "时长", dynamic: "动态", easy: "简易",
  edge: "边缘", empty: "空", enable: "启用", encode: "编码", encoder: "编码器",
  edit: "编辑", elevation: "仰角", embeds: "嵌入", end: "结束", enhance: "增强", enhancer: "增强器",
  equation: "方程", existing: "现有", expand: "扩展", export: "导出", extend: "扩展", extra: "额外",
  face: "人脸", factor: "系数", fast: "快速", file: "文件", filename: "文件名", fill: "填充", find: "查找", flip: "翻转", font: "字体", full: "完整",
  filter: "滤镜", final: "最终", first: "首个", float: "浮点数", flow: "流程", folder: "文件夹",
  for: "用于", force: "强制", format: "格式", fps: "帧率", frame: "帧", free: "释放",
  from: "从", function: "函数", gen: "生成", generate: "生成", generation: "生成", generator: "生成器",
  get: "获取", gradient: "梯度", grid: "网格", group: "分组", guidance: "引导", guide: "引导", guider: "引导器",
  height: "高度", hex: "十六进制", hook: "钩子", image: "图像", images: "图像", img: "图像", import: "导入",
  id: "ID", in: "输入", index: "索引", info: "信息", init: "初始", initial: "初始", input: "输入", insert: "插入",
  int: "整数", integer: "整数", interpolation: "插值", inpaint: "局部重绘",
  invert: "反转", json: "JSON", key: "键", keyframe: "关键帧", latent: "潜空间",
  last: "最后", level: "级别", limit: "限制", link: "链接", list: "列表",
  load: "加载", loader: "加载器", lora: "LoRA", mask: "遮罩", masks: "遮罩",
  memory: "内存", merge: "合并", metadata: "元数据", mode: "模式", model: "模型",
  multiple: "多个", name: "名称", names: "名称", negative: "负向", node: "节点",
  noise: "噪声", normalize: "标准化", number: "数值", offload: "卸载", open: "打开",
  option: "选项", output: "输出", padding: "边距", path: "路径", positive: "正向",
  precision: "精度", preprocess: "预处理", preprocessor: "预处理器", preview: "预览",
  prompt: "提示词", purge: "清理", quality: "质量", random: "随机", range: "范围",
  raw: "原始", reader: "读取器", rebalance: "再平衡", remove: "移除", rename: "重命名",
  repeat: "重复", replace: "替换", resize: "缩放", resolution: "分辨率", restore: "修复",
  reverse: "反向", rotate: "旋转", sampler: "采样器", sampling: "采样", save: "保存",
  scale: "缩放", scheduler: "调度器", seed: "种子", select: "选择", selector: "选择器",
  set: "设置", setting: "设置", sigma: "Sigma", simple: "简易", size: "尺寸",
  source: "源", start: "起始", status: "状态", step: "步", steps: "步数",
  string: "文本", style: "风格", switch: "切换", target: "目标", text: "文本",
  threshold: "阈值", tile: "分块", tiled: "分块", time: "时间", timestep: "时间步", trigger: "触发",
  tool: "工具", tooltip: "提示", total: "总计", transform: "变换", transparent: "透明",
  unload: "卸载", upscale: "放大", upscaler: "放大器", use: "使用", value: "值",
  values: "值", video: "视频", view: "查看", visualizer: "可视化器", vram: "显存",
  width: "宽度", wildcard: "通配符", with: "与", without: "不使用", write: "写入",
  reference: "参考", segment: "分段", strength: "强度", preset: "预设", max: "最大",
  weight: "权重", token: "令牌", tokens: "令牌", frames: "帧", pose: "姿态", top: "顶部",
  overlap: "重叠", filename: "文件名", chat: "对话", language: "语言", method: "方法",
  type: "类型", factor: "系数", font: "字体", new: "新", prefix: "前缀", samples: "样本",
  temperature: "温度", debug: "调试", message: "消息", messages: "消息", min: "最小",
  multi: "多重", clone: "克隆", patch: "补丁", penalty: "惩罚", repetition: "重复",
  rule: "规则", track: "跟踪", attention: "注意力", boundary: "边界", guidance: "引导",
  keep: "保留", layer: "层", layers: "层", num: "数量", angle: "角度", bbox: "边界框",
  context: "上下文", framing: "构图", loaded: "已加载", only: "仅", ref: "参考",
  separator: "分隔符", voice: "语音", any: "任意", chunk: "分块", edit: "编辑",
  fix: "修复", length: "长度", long: "长", match: "匹配", transformer: "Transformer",
  completion: "补全", content: "内容", effect: "效果", guider: "引导器", indices: "索引",
  old: "旧", plan: "方案", position: "位置", seam: "接缝", speaker: "说话人",
  stack: "堆栈", summary: "摘要", tilt: "倾斜", client: "客户端", compile: "编译",
  contrast: "对比度", dir: "目录", dtype: "数据类型", echo: "回声", experimental: "实验性",
  multiplier: "乘数", override: "覆盖", report: "报告", rescale: "重新缩放",
  return: "返回", sample: "样本", service: "服务", terms: "术语", translate: "翻译",
  used: "已使用", vector: "向量", after: "之后", bypass: "绕过", camera: "相机",
  category: "分类", correction: "校正", divider: "分隔线", half: "半精度",
  keyword: "关键词", merged: "已合并", original: "原始", out: "输出", palette: "调色板",
  rate: "速率", schedule: "调度", selected: "已选择",
  sharpness: "锐度", similarity: "相似度", skip: "跳过", sort: "排序", temporal: "时间",
  timestamp: "时间戳", timestamps: "时间戳", verbose: "详细", aligner: "对齐器",
  allow: "允许", alternative: "替代", anchor: "锚点", boost: "增强", builder: "构建器",
  cap: "上限", check: "检查", clear: "清除", delimiter: "分隔符", direction: "方向",
  distance: "距离", drop: "丢弃", embedding: "嵌入", enforce: "强制", full: "完整",
  grid: "网格", id: "ID", identity: "身份", inpaint: "局部重绘", interpolation: "插值",
  iterative: "迭代", label: "标签", local: "本地", missing: "缺失", operation: "操作",
  params: "参数", performance: "性能", ratio: "比例", refiner: "精修器", reset: "重置",
  role: "角色", semantic: "语义", speech: "语音", split: "拆分", table: "表格",
  terminology: "术语", timeline: "时间线", transcribe: "转录", trim: "修剪", vision: "视觉",
  zip: "压缩", per: "每", to: "到", of: "的", in: "中", if: "如果", when: "当",
  int: "整数", utils: "工具", base: "基础", spectral: "频谱", blue: "蓝色", green: "绿色",
  magenta: "品红色", red: "红色", yellow: "黄色", engineer: "工程器", mul: "乘数",
  anything: "任意内容", hand: "手部", object: "对象", objects: "对象", calibrator: "校准器",
  canvas: "画布", chinese: "中文", combination: "组合", conversion: "转换", creativity: "创意",
  cropped: "已裁剪", customization: "自定义", enabled: "启用", fixed: "固定", flush: "清空",
  fourth: "第四", fovea: "中央视区", frequency: "频率", fuse: "融合", gc: "垃圾回收",
  hash: "哈希", history: "历史", injector: "注入器", lying: "躺姿", megapixels: "百万像素",
  probe: "探测", proxy: "代理", reasoning: "推理", sanitize: "清理", saved: "已保存",
  scheduled: "已调度", second: "第二", sitting: "坐姿", steering: "引导", strip: "去除",
  third: "第三", tiles: "瓦片", translated: "已翻译", activation: "激活", actor: "执行器",
  additional: "附加", adjust: "调整", adjusted: "已调整", aesthetics: "美学", always: "总是",
  and: "和", append: "追加", arm: "手臂", assembly: "组合", at: "在", autotune: "自动调优",
  backbone: "骨干", behaviour: "行为", bias: "偏置", block: "区块", body: "身体",
  bound: "边界", case: "情况", causal: "因果", cleaner: "清理器", closed: "关闭",
  colored: "彩色", colour: "颜色", converter: "转换器", coord: "坐标", current: "当前",
  curves: "曲线", dehaze: "去雾", density: "密度", deprecated: "已弃用", design: "设计",
  detection: "检测", diff: "差异", dim: "维度", director: "导演", dirname: "目录名",
  disabled: "禁用", discover: "发现", divisible: "可整除", downscale: "缩小", driving: "驱动",
  editor: "编辑器", elements: "元素", encoded: "已编码", enhanced: "已增强", entries: "条目",
  error: "错误", estimate: "估算", every: "每个", exclude: "排除", expanded: "已扩展",
  extended: "已延长", external: "外部", extra: "额外", extractor: "提取器", filled: "已填充",
  flip: "翻转", forced: "强制", forward: "前向", found: "已找到", functional: "功能性",
  functions: "函数", gate: "门控", gated: "门控", gating: "门控", gaze: "凝视",
  general: "通用", grounded: "定位", grounding: "定位", guides: "引导",
  head: "头部", high: "高", hint: "提示", histogram: "直方图", human: "人体",
  inference: "推理", init: "初始化", instruct: "指令", intensity: "强度", internal: "内部",
  interval: "间隔", layout: "布局", left: "左", lighting: "光照", limb: "肢体",
  lineart: "线稿", loop: "循环", lower: "下限", manager: "管理器", manual: "手动",
  markdown: "Markdown", media: "媒体", medium: "中", mirror: "镜像", mixer: "混合器",
  mixing: "混合", multiply: "乘法", note: "备注", opacity: "不透明度", order: "顺序",
  outpainting: "扩图", package: "包", pair: "对", param: "参数", pass: "传递",
  passthrough: "直通", patcher: "补丁器", pause: "暂停", phase: "阶段", photo: "照片",
  pipe: "管道", placement: "放置", planner: "规划器", plugin: "插件",
  absolute: "绝对", av: "音视频", bg: "背景", bgcolor: "背景颜色", compine: "合并",
  completeion: "补全", cond: "条件", conv: "卷积", cos: "余弦", eff: "效率",
  inertia: "惯性", inputcount: "输入数量", kwargs: "关键字参数", mat: "矩阵",
  meaningless: "无意义", mem: "内存", mkdir: "创建目录", msg: "消息", multiangle: "多角度",
  mutiple: "多个", norm: "标准化", not: "非", nth: "第N个", optimizations: "优化",
  plus: "加", power: "功率", primitive: "基础类型", print: "打印", processed: "已处理",
  prompter: "提示器", px: "像素", quantization: "量化", randomness: "随机性", rating: "评分",
  re: "重新", read: "读取", reinforcer: "增强器", remap: "重映射", renormalize: "重新标准化",
  replacement: "替换项", repo: "仓库", restored: "已恢复", retain: "保留", retries: "重试次数",
  returned: "已返回", right: "右", route: "路由", savename: "保存名称", scaling: "缩放",
  scene: "场景", screenshot: "截图", search: "搜索", sensitive: "敏感", seq: "序列",
  sequence: "序列", setter: "设置器", shards: "分片", shift: "偏移", slot: "插槽",
  spatial: "空间", stabilizer: "稳定器", stacker: "堆叠器", standalone: "独立",
  standard: "标准", startup: "启动", stop: "停止", strategy: "策略", strict: "严格",
  stride: "步幅", sub: "子", subfolder: "子文件夹", substring: "子字符串", super: "超级",
  suppress: "抑制", synth: "合成", tags: "标签", temp: "临时", testing: "测试",
  textbox: "文本框", textfile: "文本文件", thumb: "缩略图", timeout: "超时", torso: "躯干",
  transcriptions: "转录文本", truncate: "截断", two: "双", ultimate: "终极", uniform: "均匀",
  uninjector: "取消注入器", units: "单位", universal: "通用", unscale: "反缩放",
  unzip: "解压", upscaled: "已放大", utility: "工具", variation: "变化", virtual: "虚拟",
  visual: "可视", visualize: "可视化", volume: "音量", whole: "整体", widget: "控件",
  window: "窗口", windows: "窗口", word: "单词", wrapper: "封装器", zero: "零", zoom: "缩放",
  last: "最后", layer: "层", layers: "层", learning: "学习", left: "左", legacy: "旧版", length: "长度",
  level: "级别", lighting: "光照", limit: "限制", line: "线", link: "链接", list: "列表",
  load: "加载", loader: "加载器", lora: "LoRA", loss: "损失", map: "映射", mask: "遮罩", masked: "已遮罩", masks: "遮罩",
  math: "数学", max: "最大", mean: "均值", medium: "媒介", memory: "内存", merge: "合并", metadata: "元数据",
  method: "方法", middle: "中间", min: "最小", mode: "模式", model: "模型", motion: "运动", multi: "多重", net: "网络",
  multiplier: "倍数", multiple: "多个", name: "名称", names: "名称", neg: "负向", negative: "负向", node: "节点", norm: "归一化", num: "数量",
  noise: "噪声", normalize: "标准化", number: "数值", offset: "偏移", offload: "卸载", offloading: "卸载",
  on: "开启", only: "仅", open: "打开", operation: "操作", optimizer: "优化器", opt: "可选", option: "选项", optional: "可选", original: "原始",
  order: "顺序", out: "输出", output: "输出", overlap: "重叠", override: "覆盖", pad: "填充", padding: "边距",
  palette: "调色板", panel: "面板", parameters: "参数", patch: "补丁", patcher: "补丁器", path: "路径", pattern: "模式", percent: "百分比",
  pipe: "管线", pixels: "像素", plot: "绘图", pos: "正向", pose: "姿态", positive: "正向", power: "强度", pre: "预先", prefix: "前缀", preset: "预设",
  precision: "精度", preprocess: "预处理", preprocessor: "预处理器", preview: "预览", provider: "提供方",
  prompt: "提示词", purge: "清理", quality: "质量", quantized: "量化", random: "随机", range: "范围", rank: "秩", ratio: "比例",
  raw: "原始", reader: "读取器", rebalance: "再平衡", reference: "参考", ref: "参考", refiner: "精修器", region: "区域", rescale: "重新缩放",
  remove: "移除", rename: "重命名", res: "分辨率", right: "右", rotation: "旋转",
  repeat: "重复", replace: "替换", resize: "缩放", resolution: "分辨率", restore: "修复", return: "返回",
  reverse: "反向", rotate: "旋转", sampler: "采样器", samples: "样本", sampling: "采样", save: "保存",
  scale: "缩放", schedule: "调度", scheduler: "调度器", second: "第二", seed: "种子", seg: "分割", segment: "分割", segs: "分割区域",
  select: "选择", selector: "选择器", sequence: "序列", shard: "分片", shadow: "阴影", shift: "偏移", single: "单个", skip: "跳过", slice: "切片",
  set: "设置", setting: "设置", sigma: "Sigma", sigmas: "Sigma", similarity: "相似度", simple: "简易", size: "尺寸",
  solver: "求解器", source: "源", spacing: "间距", split: "拆分", stack: "堆栈", stage: "阶段", start: "起始",
  stats: "统计信息", status: "状态", std: "标准差", step: "步", steps: "步数", stop: "停止", str: "字符串",
  strength: "强度", string: "字符串", style: "风格", suffix: "后缀", swap: "交换", switch: "切换", sync: "同步", target: "目标", temporal: "时序", text: "文本", texture: "纹理",
  threshold: "阈值", tile: "分块", tiled: "分块", time: "时间", timestep: "时间步", to: "到", top: "顶部", track: "跟踪", training: "训练", translate: "翻译", trigger: "触发", turbo: "极速", type: "类型",
  tokens: "词元", tool: "工具", tooltip: "提示", total: "总计", transform: "变换", transformer: "Transformer", transparent: "透明", truncate: "截断", txt: "文本",
  unary: "一元", unique: "唯一", unload: "卸载", unmasked: "未遮罩", upscale: "放大", upscaler: "放大器", use: "使用", utility: "工具", value: "值",
  values: "值", vec: "向量", video: "视频", view: "查看", visual: "可视化", visualizer: "可视化器", vram: "显存",
  weight: "权重", weights: "权重", width: "宽度", wildcard: "通配符", with: "与", without: "不使用", write: "写入", zero: "零"
});

export const BRANDS = Object.freeze({
  api: "API", cfg: "CFG", clip: "CLIP", cpu: "CPU", cuda: "CUDA", fp16: "FP16",
  fp32: "FP32", gpu: "GPU", json: "JSON", ksampler: "KSampler", llm: "LLM",
  lora: "LoRA", nsfw: "NSFW", png: "PNG", rgb: "RGB", sdxl: "SDXL",
  url: "URL", vae: "VAE", vram: "VRAM", qwen: "Qwen", krea: "Krea", stg: "STG",
  tts: "TTS", ltx: "LTX", ltxv: "LTXV", openai: "OpenAI", gemma: "Gemma", te: "TE",
  ui: "UI", sam: "SAM", str: "STR", ideogram: "Ideogram", ollama: "Ollama", scail: "SCAIL",
  wan: "Wan", afl: "AFL", gguf: "GGUF", ibias: "iBias", sha: "SHA", vlm: "VLM",
  asr: "ASR", comfy: "ComfyUI", dmd: "DMD", ffn: "FFN", flux: "FLUX", gpt: "GPT",
  sd: "SD", hf: "HF", psd: "PSD", ai: "AI", di: "Di", lo: "Lo", ra: "RA",
  turbo: "Turbo", sage: "SAGE", kj: "KJ", civitai: "Civitai", fish: "Fish", ostris: "Ostris",
  flash: "Flash", canny: "Canny", ffmpeg: "FFmpeg", jpeg: "JPEG", kontext: "Kontext",
  comfyui: "ComfyUI", nunchaku: "Nunchaku", aitk: "AITK", attn: "Attn", bf: "BF",
  coris: "CORIS", crf: "CRF", diffusers: "Diffusers", fooocus: "Fooocus", fp: "FP",
  freenoise: "FreeNoise", ha: "HA", kv: "KV", ly: "Ly", pi: "PI", rope: "RoPE",
  rtx: "RTX", safetensors: "SafeTensors", seedvr: "SeedVR", silu: "SiLU", sn: "SN",
  srt: "SRT", triton: "Triton", vl: "VL", wh: "宽高",
  url: "URL", vae: "VAE", vram: "VRAM", controlnet: "ControlNet", flux: "FLUX",
  hunyuan: "混元", kling: "可灵", krea: "Krea", ltx: "LTX", ltxv: "LTXV", qwen: "Qwen",
  sam: "SAM", sde: "SDE", torch: "Torch", wan: "Wan", clown: "Clown"
});
