// High-frequency ComfyUI vocabulary used only when no curated dictionary entry exists.
// Product/model names are deliberately preserved.
export const PHRASES = Object.freeze({
  "custom data reader": "自定义数据读取器",
  "triggerwords": "LoRA 触发词",
  "trigger words": "触发词",
  "lora trigger words": "LoRA 触发词",
  "load images for loop": "加载图像并循环",
  "load image": "加载图像",
  "save image": "保存图像",
  "load model": "加载模型",
  "model loader": "模型加载器",
  "lora loader": "LoRA 加载器",
  "vae loader": "VAE 加载器",
  "control net": "ControlNet",
  "control net loader": "ControlNet 加载器",
  "text encode": "文本编码",
  "text encoder": "文本编码器",
  "image batch": "图像批次",
  "batch size": "批次大小",
  "image size": "图像尺寸",
  "width and height": "宽度和高度",
  "positive prompt": "正向提示词",
  "negative prompt": "负向提示词",
  "start index": "起始索引",
  "end index": "结束索引",
  "initial value": "初始值",
  "preview image": "预览图像",
  "custom prompt": "自定义提示词",
  "model description": "模型描述",
  "download link": "下载链接",
  "raw json": "原始 JSON",
  "file name": "文件名",
  "file path": "文件路径",
  "output path": "输出路径",
  "input image": "输入图像",
  "output image": "输出图像",
  "source image": "源图像",
  "target image": "目标图像",
  "random seed": "随机种子",
  "sampling steps": "采样步数",
  "frame rate": "帧率",
  "frame count": "帧数",
  "first frame": "首帧",
  "last frame": "尾帧",
  "audio file": "音频文件",
  "video file": "视频文件",
  "system prompt": "系统提示词",
  "user prompt": "用户提示词",
  "base model": "基础模型",
  "output model": "输出模型",
  "input directory": "输入目录",
  "output directory": "输出目录",
  "keep aspect ratio": "保持宽高比",
  "aspect ratio": "宽高比",
  "resize mode": "缩放模式",
  "crop mode": "裁剪模式",
  "blend mode": "混合模式",
  "mask mode": "遮罩模式",
  "color space": "色彩空间",
  "device mode": "设备模式",
  "precision mode": "精度模式",
  "clear cache": "清理缓存",
  "free memory": "释放内存",
  "enable preview": "启用预览",
  "force offload": "强制卸载",
  "use cache": "使用缓存",
  "default value": "默认值"
});

export const WORDS = Object.freeze({
  a: "一个", add: "添加", advanced: "高级", align: "对齐", alpha: "透明度",
  amount: "数量", analyze: "分析", apply: "应用", area: "区域", audio: "音频",
  auto: "自动", background: "背景", batch: "批次", blend: "混合", blur: "模糊",
  boolean: "布尔值", box: "框", brightness: "亮度", cache: "缓存", calculate: "计算",
  caption: "描述", channel: "通道", checkpoint: "检查点模型", choose: "选择", clean: "清理",
  clip: "CLIP", color: "颜色", combine: "合并", compact: "紧凑", compare: "比较",
  complete: "补全", compress: "压缩", concatenate: "拼接", concat: "拼接", condition: "条件",
  conditioning: "条件", config: "配置", control: "控制", convert: "转换", copy: "复制",
  count: "数量", create: "创建", crop: "裁剪", custom: "自定义", data: "数据",
  decode: "解码", decoder: "解码器", default: "默认", delete: "删除", denoise: "降噪",
  depth: "深度", description: "描述", detect: "检测", device: "设备", directory: "目录",
  disable: "禁用", download: "下载", duration: "时长", dynamic: "动态", easy: "简易",
  edge: "边缘", empty: "空", enable: "启用", encode: "编码", encoder: "编码器",
  end: "结束", enhance: "增强", enhancer: "增强器", equation: "方程", expand: "扩展",
  export: "导出", face: "人脸", fast: "快速", file: "文件", fill: "填充",
  filter: "滤镜", first: "首个", float: "浮点数", flow: "流程", folder: "文件夹",
  force: "强制", format: "格式", fps: "帧率", frame: "帧", free: "释放",
  from: "从", generate: "生成", generator: "生成器", get: "获取", group: "分组",
  height: "高度", hook: "钩子", image: "图像", images: "图像", import: "导入",
  index: "索引", info: "信息", initial: "初始", input: "输入", integer: "整数",
  invert: "反转", json: "JSON", key: "键", keyframe: "关键帧", latent: "潜空间",
  last: "最后", level: "级别", limit: "限制", link: "链接", list: "列表",
  load: "加载", loader: "加载器", lora: "LoRA", mask: "遮罩", masks: "遮罩",
  memory: "内存", merge: "合并", metadata: "元数据", mode: "模式", model: "模型",
  multiple: "多个", name: "名称", names: "名称", negative: "负向", node: "节点",
  noise: "噪声", normalize: "标准化", number: "数值", offload: "卸载", open: "打开",
  option: "选项", output: "输出", padding: "边距", path: "路径", positive: "正向",
  precision: "精度", preprocess: "预处理", preprocessor: "预处理器", preview: "预览",
  prompt: "提示词", purge: "清理", quality: "质量", random: "随机", range: "范围",
  raw: "原始", reader: "读取器", rebalance: "再平衡", remove: "移除", rename: "重命名",
  repeat: "重复", replace: "替换", resize: "缩放", resolution: "分辨率", restore: "修复",
  reverse: "反向", rotate: "旋转", sampler: "采样器", sampling: "采样", save: "保存",
  scale: "缩放", scheduler: "调度器", seed: "种子", select: "选择", selector: "选择器",
  set: "设置", setting: "设置", sigma: "Sigma", simple: "简易", size: "尺寸",
  source: "源", start: "起始", status: "状态", step: "步", steps: "步数",
  string: "文本", style: "风格", switch: "切换", target: "目标", text: "文本",
  threshold: "阈值", tile: "分块", tiled: "分块", time: "时间", timestep: "时间步", trigger: "触发",
  tool: "工具", tooltip: "提示", total: "总计", transform: "变换", transparent: "透明",
  unload: "卸载", upscale: "放大", upscaler: "放大器", use: "使用", value: "值",
  values: "值", video: "视频", view: "查看", visualizer: "可视化器", vram: "显存",
  width: "宽度", wildcard: "通配符", with: "与", without: "不使用", write: "写入"
});

export const BRANDS = Object.freeze({
  api: "API", cfg: "CFG", clip: "CLIP", cpu: "CPU", cuda: "CUDA", fp16: "FP16",
  fp32: "FP32", gpu: "GPU", json: "JSON", ksampler: "KSampler", llm: "LLM",
  lora: "LoRA", nsfw: "NSFW", png: "PNG", rgb: "RGB", sdxl: "SDXL",
  url: "URL", vae: "VAE", vram: "VRAM"
});
